server:
  port: 8081

spring:
  application:
    name: aftersale-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/oomall?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000 # 10 minutes
      keepalive-time: 30000 # 30 seconds
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    cn.edu.xmu.oomall: DEBUG
